### ISSUE TITLE
Securing the backend infrastructure and HTTP headers from cross side scripting and cross side injection attacks.

### ISSUE THREAD

**Issue by Ayush-projects** [mrmodise/nodejs-ecommerce-store#13]
Can I start working on this issue?

**Comment by mrmodise** [comment]
Hi, thanks for your interest. Please go ahead

**Comment by Ayush-projects** [comment]
Hello please assign me this issue and please assign the issue number in my PR request, I have already made pull request.

**Comment by mrmodise** [comment]
You just needed to add #13

**Comment by Ayush-projects** [comment]
Hello, thanks for linking the issue, I have to share the link of this pull
request to my course instructor. I will be adding prettier in the next pull
request, meanwhile can you please merge it, as it's very important for me,
I will add prettier in the next PR for sure maybe today itself.

**Comment by Ayush-projects** [comment]
Can you review and merge my PR, adding prettier in the next PR?
