### ISSUE TITLE
Search Functionality not working

### ISSUE THREAD

**Issue by ghost** [mrmodise/nodejs-ecommerce-store#3]
When i run your website, no products listed, or cant add products. When i search something its giving timeout error

Error: Request Timeout after 30000ms
    at /home/rekhakalasre/Downloads/nodejs-ecommerce-store-master/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:362:15
    at Timeout.<anonymous> (/home/rekhakalasre/Downloads/nodejs-ecommerce-store-master/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:391:7)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)

**Comment by mrmodise** [comment]
> When i run your website, no products listed, or cant add products. When i search something its giving timeout error
> 
> Error: Request Timeout after 30000ms
> at /home/rekhakalasre/Downloads/nodejs-ecommerce-store-master/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:362:15
> at Timeout. (/home/rekhakalasre/Downloads/nodejs-ecommerce-store-master/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:391:7)
> at listOnTimeout (internal/timers.js:535:17)
> at processTimers (internal/timers.js:479:7)

Thanks please refer to the testing section. You need to add data for the search functionality to work. Also make sure eleasticsearch and mongodb are up and running

**Comment by mrmodise** [comment]
I trust the above helped you
